---
- include_tasks: setup-debian-9.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '9'

- group: name={{ parity_group }} system=yes state=present
- user: name={{ parity_user }} group={{ parity_group }} home={{ parity_home }} state=present

- name: "parity home ownership"
  file:
    path: "{{ parity_home }}/"
    owner: "{{ parity_user }}"
    group: "{{ parity_group }}"
    state: directory
    recurse: yes

- name: "remove old parity package (no longer supported)"
  package:
    name: parity
    state: absent

- name: "check installed parity version"
  shell: "parity --version | grep 'version Parity' | sed -n -E -e 's/.*version Parity\/v([0-9\\.]*)-.*/\\1/p'"
  register: parity_version
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- set_fact: parity_installed={{ parity_version.stdout_lines[0] is defined and parity_version.stdout_lines[0] == parity_version_string }}

- name: "download parity bin file"
  get_url:
    url: "{{ parity_source }}"
    dest: "{{ parity_dst_bindir }}/parity"
    checksum: "{{ parity_sum }}"
    owner: root
    group: staff
    mode: 0755
  when: not parity_installed
  notify:
    - stop parity

- name: "parity config file"
  template:
    src: templates/parity_config.toml.j2
    dest: "{{ parity_home }}/config.toml"
    owner: "{{ parity_user }}"
    group: "{{ parity_group }}"
    mode: 0644
  notify:
    - stop parity

- block:
  - name: "copy chain file"
    copy: src={{ parity_chain_file }} dest={{ parity_home }} owner={{ parity_user }} group={{ parity_group }} mode=0644
  - name: "set parity command line args for chainfile"
    set_fact: parity_extra_args="--chain {{ parity_home }}/{{ parity_chain_file | basename }} {{ parity_extra_args }}"
  when: parity_chain_file is defined and parity_chain_file

- name: "systemd parity service configuration file"
  template: src=templates/parity.service.j2 dest=/etc/systemd/system/{{ systemd_service_name }}.service owner=root group=root mode=0644
  notify:
    - reload systemd

- name: "sync parity data"
  import_tasks: sync-blockchain.yml
  tags: sync-parity-data
  when: not( (sync_data_from is undefined) or (sync_data_from is none) or (sync_data_from | trim == '') )

- name: "parity key dir"
  file:
    path: "{{ parity_home }}/.local/share/io.parity.ethereum/keys/{{ ethereum_accounts_files_dest }}"
    state: directory
    owner: "{{ parity_user }}"
    group: "{{ parity_group }}"
    mode: 0755

- name: "parity account key files"
  copy:
    src: "{{ item }}"
    dest: "{{ parity_home }}/.local/share/io.parity.ethereum/keys/{{ ethereum_accounts_files_dest }}/"
    owner: "{{ parity_user }}"
    group: "{{ parity_group }}"
    mode: 0600
  with_items: "{{ ethereum_accounts_files }}"

- name: "json rpc firewall"
  ufw: rule=allow port={{ parity_rpc_port }} from={{ item }}
  with_items: "{{ parity_rpc_allowed_ip }}"
  tags: firewall

- meta: flush_handlers

- name: "service parity enabled"
  service: name={{ systemd_service_name }} enabled=yes state=started

- name: "monitoring"
  import_tasks: monitoring.yml
  when: icinga_server is defined
  tags: monitoring
